export const JUSTIFY_CONTENT = {
  START: 'flex-start',
  END: 'flex-end',
  CENTER: 'center',
};

export const SWIPABLE_ITEM_WIDTH = 100;

// export const DEFAULT_COLORS_LIST = [
//   {
//     id: 1,
//     colorName: 'RED',
//     color: '#C14040',
//     colorBG: '',
//   },
//   {
//     id: 2,
//     colorName: 'ORANGE',
//     color: '#FD7F1F',
//     colorBG: '',
//   },
//   {
//     id: 3,
//     colorName: 'YELLOW',
//     color: '#E9C432',
//     colorBG: '',
//   },
//   {
//     id: 4,
//     colorName: 'GREEN',
//     color: '#2BAB64',
//     colorBG: '',
//   },
//   {
//     id: 5,
//     colorName: 'DARK_BLUE',
//     color: '#2B5D95',
//     colorBG: '',
//   },
//   {
//     id: 6,
//     colorName: 'VIOLET',
//     color: '#9682C8',
//     colorBG: '',
//   },
//   {
//     id: 7,
//     colorName: 'LIGHT_BLUE',
//     color: '#5DC1EA',
//     colorBG: '',
//   },
//   {
//     id: 8,
//     colorName: 'GREY',
//     color: '#707070',
//     colorBG: '',
//   },
// ];

export const DEFAULT_COLORS_LIST = [
  {
    id: 1,
    colorName: 'LIGHTEST_GREEN',
    color: '#77bb77',
    colorBG: '',
  },
  {
    id: 2,
    colorName: 'LIGHTER_GREEN',
    color: '#559955',
    colorBG: '',
  },
  {
    id: 3,
    colorName: 'GREEN',
    color: '#40916c',
    colorBG: '',
  },
  {
    id: 4,
    colorName: 'DARKER_GREEN',
    color: '#006f5f',
    colorBG: '',
  },
  {
    id: 5,
    colorName: 'DARKEST_GREEN',
    color: '#006000',
    colorBG: '',
  },
];

// export const DEFAULT_COLOR_INDEX = {
//   RED: 0,
//   ORANGE: 1,
//   YELLOW: 2,
//   GREEN: 3,
//   DARK_BLUE: 4,
//   VIOLET: 5,
//   LIGHT_BLUE: 6,
//   GREY: 7,
// };

export const DEFAULT_COLOR_INDEX = {
  LIGHTEST_GREEN: 0,
  LIGHTER_GREEN: 1,
  GREEN: 2,
  DARKER_GREEN: 3,
  DARKEST_GREEN: 4,
};

export const todoInitList = [
  {
    id: '01',
    name: 'Do some thing 01',
    description: 'Description for Todo list item number 01',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '02',
    name: 'Do some thing 02',
    description: 'Description for Todo list item number 02',
    color: 'DARKEST_GREEN',
  },
  {
    id: '03',
    name: 'Do some thing 03',
    description: 'Description for Todo list item number 03',
    color: 'GREEN',
  },
  {
    id: '04',
    name: 'Do some thing 04',
    description: 'Description for Todo list item number 04',
    color: 'DARKER_GREEN',
  },
  {
    id: '05',
    name: 'Do some thing 05',
    description: 'Description for Todo list item number 05',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '06',
    name: 'Do some thing 06',
    description: 'Description for Todo list item number 06',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '07',
    name: 'Do some thing 07',
    description: 'Description for Todo list item number 07',
    color: 'GREEN',
  },
  {
    id: '08',
    name: 'Do some thing 08',
    description: 'Description for Todo list item number 08',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '09',
    name: 'Do some thing 09',
    description: 'Description for Todo list item number 09',
    color: 'DARKER_GREEN',
  },
  {
    id: '10',
    name: 'Do some thing 10',
    description: 'Description for Todo list item number 10',
    color: 'GREEN',
  },
  {
    id: '11',
    name: 'Do some thing 11',
    description: 'Description for Todo list item number 11',
    color: 'DARKEST_GREEN',
  },
  {
    id: '12',
    name: 'Do some thing 12',
    description: 'Description for Todo list item number 12',
    color: 'DARKER_GREEN',
  },
  {
    id: '13',
    name: 'Do some thing 13',
    description: 'Description for Todo list item number 13',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '14',
    name: 'Do some thing 14',
    description: 'Description for Todo list item number 14',
    color: 'DARKER_GREEN',
  },
  {
    id: '15',
    name: 'Do some thing 15',
    description: 'Description for Todo list item number 15',
    color: 'GREEN',
  },
  {
    id: '16',
    name: 'Do some thing 16',
    description: 'Description for Todo list item number 16',
    color: 'DARKEST_GREEN',
  },
  {
    id: '17',
    name: 'Do some thing 17',
    description: 'Description for Todo list item number 17',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '18',
    name: 'Do some thing 18',
    description: 'Description for Todo list item number 18',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '19',
    name: 'Do some thing 19',
    description: 'Description for Todo list item number 19',
    color: 'GREEN',
  },
  {
    id: '20',
    name: 'Do some thing 20',
    description: 'Description for Todo list item number 20',
    color: 'DARKER_GREEN',
  },
];

export const LARGE_INIT_TODO_LIST = [
  {
    id: '001',
    name: 'Do some thing 001',
    description: 'Description for Todo list item number 001',
    color: 'DARKER_GREEN',
  },
  {
    id: '002',
    name: 'Do some thing 002',
    description: 'Description for Todo list item number 002',
    color: 'GREEN',
  },
  {
    id: '003',
    name: 'Do some thing 003',
    description: 'Description for Todo list item number 003',
    color: 'DARKEST_GREEN',
  },
  {
    id: '004',
    name: 'Do some thing 004',
    description: 'Description for Todo list item number 004',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '005',
    name: 'Do some thing 005',
    description: 'Description for Todo list item number 005',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '006',
    name: 'Do some thing 006',
    description: 'Description for Todo list item number 006',
    color: 'DARKER_GREEN',
  },
  {
    id: '007',
    name: 'Do some thing 007',
    description: 'Description for Todo list item number 007',
    color: 'GREEN',
  },
  {
    id: '008',
    name: 'Do some thing 008',
    description: 'Description for Todo list item number 008',
    color: 'DARKER_GREEN',
  },
  {
    id: '009',
    name: 'Do some thing 009',
    description: 'Description for Todo list item number 009',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '010',
    name: 'Do some thing 010',
    description: 'Description for Todo list item number 010',
    color: 'DARKEST_GREEN',
  },
  {
    id: '011',
    name: 'Do some thing 011',
    description: 'Description for Todo list item number 011',
    color: 'DARKER_GREEN',
  },
  {
    id: '012',
    name: 'Do some thing 012',
    description: 'Description for Todo list item number 012',
    color: 'DARKER_GREEN',
  },
  {
    id: '013',
    name: 'Do some thing 013',
    description: 'Description for Todo list item number 013',
    color: 'GREEN',
  },
  {
    id: '014',
    name: 'Do some thing 014',
    description: 'Description for Todo list item number 014',
    color: 'DARKER_GREEN',
  },
  {
    id: '015',
    name: 'Do some thing 015',
    description: 'Description for Todo list item number 015',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '016',
    name: 'Do some thing 016',
    description: 'Description for Todo list item number 016',
    color: 'DARKEST_GREEN',
  },
  {
    id: '017',
    name: 'Do some thing 017',
    description: 'Description for Todo list item number 017',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '018',
    name: 'Do some thing 018',
    description: 'Description for Todo list item number 018',
    color: 'GREEN',
  },
  {
    id: '019',
    name: 'Do some thing 019',
    description: 'Description for Todo list item number 019',
    color: 'DARKER_GREEN',
  },
  {
    id: '020',
    name: 'Do some thing 020',
    description: 'Description for Todo list item number 020',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '021',
    name: 'Do some thing 021',
    description: 'Description for Todo list item number 021',
    color: 'DARKER_GREEN',
  },
  {
    id: '022',
    name: 'Do some thing 022',
    description: 'Description for Todo list item number 022',
    color: 'GREEN',
  },
  {
    id: '023',
    name: 'Do some thing 023',
    description: 'Description for Todo list item number 023',
    color: 'DARKEST_GREEN',
  },
  {
    id: '024',
    name: 'Do some thing 024',
    description: 'Description for Todo list item number 024',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '025',
    name: 'Do some thing 025',
    description: 'Description for Todo list item number 025',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '026',
    name: 'Do some thing 026',
    description: 'Description for Todo list item number 026',
    color: 'DARKER_GREEN',
  },
  {
    id: '027',
    name: 'Do some thing 027',
    description: 'Description for Todo list item number 027',
    color: 'GREEN',
  },
  {
    id: '028',
    name: 'Do some thing 028',
    description: 'Description for Todo list item number 028',
    color: 'DARKER_GREEN',
  },
  {
    id: '029',
    name: 'Do some thing 029',
    description: 'Description for Todo list item number 029',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '030',
    name: 'Do some thing 030',
    description: 'Description for Todo list item number 030',
    color: 'DARKEST_GREEN',
  },
  {
    id: '031',
    name: 'Do some thing 031',
    description: 'Description for Todo list item number 031',
    color: 'DARKER_GREEN',
  },
  {
    id: '032',
    name: 'Do some thing 032',
    description: 'Description for Todo list item number 032',
    color: 'DARKER_GREEN',
  },
  {
    id: '033',
    name: 'Do some thing 033',
    description: 'Description for Todo list item number 033',
    color: 'GREEN',
  },
  {
    id: '034',
    name: 'Do some thing 034',
    description: 'Description for Todo list item number 034',
    color: 'DARKER_GREEN',
  },
  {
    id: '035',
    name: 'Do some thing 035',
    description: 'Description for Todo list item number 035',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '036',
    name: 'Do some thing 036',
    description: 'Description for Todo list item number 036',
    color: 'DARKEST_GREEN',
  },
  {
    id: '037',
    name: 'Do some thing 037',
    description: 'Description for Todo list item number 037',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '038',
    name: 'Do some thing 038',
    description: 'Description for Todo list item number 038',
    color: 'GREEN',
  },
  {
    id: '039',
    name: 'Do some thing 039',
    description: 'Description for Todo list item number 039',
    color: 'DARKER_GREEN',
  },
  {
    id: '040',
    name: 'Do some thing 040',
    description: 'Description for Todo list item number 040',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '041',
    name: 'Do some thing 041',
    description: 'Description for Todo list item number 041',
    color: 'DARKEST_GREEN',
  },
  {
    id: '042',
    name: 'Do some thing 042',
    description: 'Description for Todo list item number 042',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '043',
    name: 'Do some thing 043',
    description: 'Description for Todo list item number 043',
    color: 'DARKER_GREEN',
  },
  {
    id: '044',
    name: 'Do some thing 044',
    description: 'Description for Todo list item number 044',
    color: 'GREEN',
  },
  {
    id: '045',
    name: 'Do some thing 045',
    description: 'Description for Todo list item number 045',
    color: 'DARKER_GREEN',
  },
  {
    id: '046',
    name: 'Do some thing 046',
    description: 'Description for Todo list item number 046',
    color: 'DARKEST_GREEN',
  },
  {
    id: '047',
    name: 'Do some thing 047',
    description: 'Description for Todo list item number 047',
    color: 'DARKER_GREEN',
  },
  {
    id: '048',
    name: 'Do some thing 048',
    description: 'Description for Todo list item number 048',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '049',
    name: 'Do some thing 049',
    description: 'Description for Todo list item number 049',
    color: 'GREEN',
  },
  {
    id: '050',
    name: 'Do some thing 050',
    description: 'Description for Todo list item number 050',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '051',
    name: 'Do some thing 051',
    description: 'Description for Todo list item number 051',
    color: 'DARKER_GREEN',
  },
  {
    id: '052',
    name: 'Do some thing 052',
    description: 'Description for Todo list item number 052',
    color: 'DARKER_GREEN',
  },
  {
    id: '053',
    name: 'Do some thing 053',
    description: 'Description for Todo list item number 053',
    color: 'DARKEST_GREEN',
  },
  {
    id: '054',
    name: 'Do some thing 054',
    description: 'Description for Todo list item number 054',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '055',
    name: 'Do some thing 055',
    description: 'Description for Todo list item number 055',
    color: 'DARKER_GREEN',
  },
  {
    id: '056',
    name: 'Do some thing 056',
    description: 'Description for Todo list item number 056',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '057',
    name: 'Do some thing 057',
    description: 'Description for Todo list item number 057',
    color: 'GREEN',
  },
  {
    id: '058',
    name: 'Do some thing 058',
    description: 'Description for Todo list item number 058',
    color: 'DARKER_GREEN',
  },
  {
    id: '059',
    name: 'Do some thing 059',
    description: 'Description for Todo list item number 059',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '060',
    name: 'Do some thing 060',
    description: 'Description for Todo list item number 060',
    color: 'DARKEST_GREEN',
  },
  {
    id: '061',
    name: 'Do some thing 061',
    description: 'Description for Todo list item number 061',
    color: 'DARKER_GREEN',
  },
  {
    id: '062',
    name: 'Do some thing 062',
    description: 'Description for Todo list item number 062',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '063',
    name: 'Do some thing 063',
    description: 'Description for Todo list item number 063',
    color: 'DARKER_GREEN',
  },
  {
    id: '064',
    name: 'Do some thing 064',
    description: 'Description for Todo list item number 064',
    color: 'DARKEST_GREEN',
  },
  {
    id: '065',
    name: 'Do some thing 065',
    description: 'Description for Todo list item number 065',
    color: 'GREEN',
  },
  {
    id: '066',
    name: 'Do some thing 066',
    description: 'Description for Todo list item number 066',
    color: 'DARKER_GREEN',
  },
  {
    id: '067',
    name: 'Do some thing 067',
    description: 'Description for Todo list item number 067',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '068',
    name: 'Do some thing 068',
    description: 'Description for Todo list item number 068',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '069',
    name: 'Do some thing 069',
    description: 'Description for Todo list item number 069',
    color: 'DARKEST_GREEN',
  },
  {
    id: '070',
    name: 'Do some thing 070',
    description: 'Description for Todo list item number 070',
    color: 'GREEN',
  },
  {
    id: '071',
    name: 'Do some thing 071',
    description: 'Description for Todo list item number 071',
    color: 'DARKER_GREEN',
  },
  {
    id: '072',
    name: 'Do some thing 072',
    description: 'Description for Todo list item number 072',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '073',
    name: 'Do some thing 073',
    description: 'Description for Todo list item number 073',
    color: 'DARKEST_GREEN',
  },
  {
    id: '074',
    name: 'Do some thing 074',
    description: 'Description for Todo list item number 074',
    color: 'DARKER_GREEN',
  },
  {
    id: '075',
    name: 'Do some thing 075',
    description: 'Description for Todo list item number 075',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '076',
    name: 'Do some thing 076',
    description: 'Description for Todo list item number 076',
    color: 'DARKEST_GREEN',
  },
  {
    id: '077',
    name: 'Do some thing 077',
    description: 'Description for Todo list item number 077',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '078',
    name: 'Do some thing 078',
    description: 'Description for Todo list item number 078',
    color: 'GREEN',
  },
  {
    id: '079',
    name: 'Do some thing 079',
    description: 'Description for Todo list item number 079',
    color: 'DARKER_GREEN',
  },
  {
    id: '080',
    name: 'Do some thing 080',
    description: 'Description for Todo list item number 080',
    color: 'DARKER_GREEN',
  },
  {
    id: '081',
    name: 'Do some thing 081',
    description: 'Description for Todo list item number 081',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '082',
    name: 'Do some thing 082',
    description: 'Description for Todo list item number 082',
    color: 'DARKEST_GREEN',
  },
  {
    id: '083',
    name: 'Do some thing 083',
    description: 'Description for Todo list item number 083',
    color: 'DARKER_GREEN',
  },
  {
    id: '084',
    name: 'Do some thing 084',
    description: 'Description for Todo list item number 084',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '085',
    name: 'Do some thing 085',
    description: 'Description for Todo list item number 085',
    color: 'GREEN',
  },
  {
    id: '086',
    name: 'Do some thing 086',
    description: 'Description for Todo list item number 086',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '087',
    name: 'Do some thing 087',
    description: 'Description for Todo list item number 087',
    color: 'DARKER_GREEN',
  },
  {
    id: '088',
    name: 'Do some thing 088',
    description: 'Description for Todo list item number 088',
    color: 'DARKEST_GREEN',
  },
  {
    id: '089',
    name: 'Do some thing 089',
    description: 'Description for Todo list item number 089',
    color: 'DARKER_GREEN',
  },
  {
    id: '090',
    name: 'Do some thing 090',
    description: 'Description for Todo list item number 090',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '091',
    name: 'Do some thing 091',
    description: 'Description for Todo list item number 091',
    color: 'GREEN',
  },
  {
    id: '092',
    name: 'Do some thing 092',
    description: 'Description for Todo list item number 092',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '093',
    name: 'Do some thing 093',
    description: 'Description for Todo list item number 093',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '094',
    name: 'Do some thing 094',
    description: 'Description for Todo list item number 094',
    color: 'DARKEST_GREEN',
  },
  {
    id: '095',
    name: 'Do some thing 095',
    description: 'Description for Todo list item number 095',
    color: 'DARKER_GREEN',
  },
  {
    id: '096',
    name: 'Do some thing 096',
    description: 'Description for Todo list item number 096',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '097',
    name: 'Do some thing 097',
    description: 'Description for Todo list item number 097',
    color: 'GREEN',
  },
  {
    id: '098',
    name: 'Do some thing 098',
    description: 'Description for Todo list item number 098',
    color: 'DARKER_GREEN',
  },
  {
    id: '099',
    name: 'Do some thing 099',
    description: 'Description for Todo list item number 099',
    color: 'DARKEST_GREEN',
  },
  {
    id: '100',
    name: 'Do some thing 100',
    description: 'Description for Todo list item number 100',
    color: 'DARKER_GREEN',
  },

  {
    id: '101',
    name: 'Do some thing 101',
    description: 'Description for Todo list item number 101',
    color: 'DARKER_GREEN',
  },
  {
    id: '102',
    name: 'Do some thing 102',
    description: 'Description for Todo list item number 102',
    color: 'GREEN',
  },
  {
    id: '103',
    name: 'Do some thing 103',
    description: 'Description for Todo list item number 103',
    color: 'DARKEST_GREEN',
  },
  {
    id: '104',
    name: 'Do some thing 104',
    description: 'Description for Todo list item number 104',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '105',
    name: 'Do some thing 105',
    description: 'Description for Todo list item number 105',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '106',
    name: 'Do some thing 106',
    description: 'Description for Todo list item number 106',
    color: 'DARKER_GREEN',
  },
  {
    id: '107',
    name: 'Do some thing 107',
    description: 'Description for Todo list item number 107',
    color: 'GREEN',
  },
  {
    id: '108',
    name: 'Do some thing 108',
    description: 'Description for Todo list item number 108',
    color: 'DARKER_GREEN',
  },
  {
    id: '109',
    name: 'Do some thing 109',
    description: 'Description for Todo list item number 109',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '110',
    name: 'Do some thing 110',
    description: 'Description for Todo list item number 110',
    color: 'DARKEST_GREEN',
  },
  {
    id: '111',
    name: 'Do some thing 111',
    description: 'Description for Todo list item number 111',
    color: 'DARKER_GREEN',
  },
  {
    id: '112',
    name: 'Do some thing 112',
    description: 'Description for Todo list item number 112',
    color: 'DARKER_GREEN',
  },
  {
    id: '113',
    name: 'Do some thing 113',
    description: 'Description for Todo list item number 113',
    color: 'GREEN',
  },
  {
    id: '114',
    name: 'Do some thing 114',
    description: 'Description for Todo list item number 114',
    color: 'DARKER_GREEN',
  },
  {
    id: '115',
    name: 'Do some thing 115',
    description: 'Description for Todo list item number 115',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '116',
    name: 'Do some thing 116',
    description: 'Description for Todo list item number 116',
    color: 'DARKEST_GREEN',
  },
  {
    id: '117',
    name: 'Do some thing 117',
    description: 'Description for Todo list item number 117',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '118',
    name: 'Do some thing 118',
    description: 'Description for Todo list item number 118',
    color: 'GREEN',
  },
  {
    id: '119',
    name: 'Do some thing 119',
    description: 'Description for Todo list item number 119',
    color: 'DARKER_GREEN',
  },
  {
    id: '120',
    name: 'Do some thing 120',
    description: 'Description for Todo list item number 120',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '121',
    name: 'Do some thing 121',
    description: 'Description for Todo list item number 121',
    color: 'DARKER_GREEN',
  },
  {
    id: '122',
    name: 'Do some thing 122',
    description: 'Description for Todo list item number 122',
    color: 'GREEN',
  },
  {
    id: '123',
    name: 'Do some thing 123',
    description: 'Description for Todo list item number 123',
    color: 'DARKEST_GREEN',
  },
  {
    id: '124',
    name: 'Do some thing 124',
    description: 'Description for Todo list item number 124',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '125',
    name: 'Do some thing 125',
    description: 'Description for Todo list item number 125',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '126',
    name: 'Do some thing 126',
    description: 'Description for Todo list item number 126',
    color: 'DARKER_GREEN',
  },
  {
    id: '127',
    name: 'Do some thing 127',
    description: 'Description for Todo list item number 127',
    color: 'GREEN',
  },
  {
    id: '128',
    name: 'Do some thing 128',
    description: 'Description for Todo list item number 128',
    color: 'DARKER_GREEN',
  },
  {
    id: '129',
    name: 'Do some thing 129',
    description: 'Description for Todo list item number 129',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '130',
    name: 'Do some thing 130',
    description: 'Description for Todo list item number 130',
    color: 'DARKEST_GREEN',
  },
  {
    id: '131',
    name: 'Do some thing 131',
    description: 'Description for Todo list item number 131',
    color: 'DARKER_GREEN',
  },
  {
    id: '132',
    name: 'Do some thing 132',
    description: 'Description for Todo list item number 132',
    color: 'DARKER_GREEN',
  },
  {
    id: '133',
    name: 'Do some thing 133',
    description: 'Description for Todo list item number 133',
    color: 'GREEN',
  },
  {
    id: '134',
    name: 'Do some thing 134',
    description: 'Description for Todo list item number 134',
    color: 'DARKER_GREEN',
  },
  {
    id: '135',
    name: 'Do some thing 135',
    description: 'Description for Todo list item number 135',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '136',
    name: 'Do some thing 136',
    description: 'Description for Todo list item number 136',
    color: 'DARKEST_GREEN',
  },
  {
    id: '137',
    name: 'Do some thing 137',
    description: 'Description for Todo list item number 137',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '138',
    name: 'Do some thing 138',
    description: 'Description for Todo list item number 138',
    color: 'GREEN',
  },
  {
    id: '139',
    name: 'Do some thing 139',
    description: 'Description for Todo list item number 139',
    color: 'DARKER_GREEN',
  },
  {
    id: '140',
    name: 'Do some thing 140',
    description: 'Description for Todo list item number 140',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '141',
    name: 'Do some thing 141',
    description: 'Description for Todo list item number 141',
    color: 'DARKEST_GREEN',
  },
  {
    id: '142',
    name: 'Do some thing 142',
    description: 'Description for Todo list item number 142',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '143',
    name: 'Do some thing 143',
    description: 'Description for Todo list item number 143',
    color: 'DARKER_GREEN',
  },
  {
    id: '144',
    name: 'Do some thing 144',
    description: 'Description for Todo list item number 144',
    color: 'GREEN',
  },
  {
    id: '145',
    name: 'Do some thing 145',
    description: 'Description for Todo list item number 145',
    color: 'DARKER_GREEN',
  },
  {
    id: '146',
    name: 'Do some thing 146',
    description: 'Description for Todo list item number 146',
    color: 'DARKEST_GREEN',
  },
  {
    id: '147',
    name: 'Do some thing 147',
    description: 'Description for Todo list item number 147',
    color: 'DARKER_GREEN',
  },
  {
    id: '148',
    name: 'Do some thing 148',
    description: 'Description for Todo list item number 148',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '149',
    name: 'Do some thing 149',
    description: 'Description for Todo list item number 149',
    color: 'GREEN',
  },
  {
    id: '150',
    name: 'Do some thing 150',
    description: 'Description for Todo list item number 150',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '151',
    name: 'Do some thing 151',
    description: 'Description for Todo list item number 151',
    color: 'DARKER_GREEN',
  },
  {
    id: '152',
    name: 'Do some thing 152',
    description: 'Description for Todo list item number 152',
    color: 'DARKER_GREEN',
  },
  {
    id: '153',
    name: 'Do some thing 153',
    description: 'Description for Todo list item number 153',
    color: 'DARKEST_GREEN',
  },
  {
    id: '154',
    name: 'Do some thing 154',
    description: 'Description for Todo list item number 154',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '155',
    name: 'Do some thing 155',
    description: 'Description for Todo list item number 155',
    color: 'DARKER_GREEN',
  },
  {
    id: '156',
    name: 'Do some thing 156',
    description: 'Description for Todo list item number 156',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '157',
    name: 'Do some thing 157',
    description: 'Description for Todo list item number 157',
    color: 'GREEN',
  },
  {
    id: '158',
    name: 'Do some thing 158',
    description: 'Description for Todo list item number 158',
    color: 'DARKER_GREEN',
  },
  {
    id: '159',
    name: 'Do some thing 159',
    description: 'Description for Todo list item number 159',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '160',
    name: 'Do some thing 160',
    description: 'Description for Todo list item number 160',
    color: 'DARKEST_GREEN',
  },
  {
    id: '161',
    name: 'Do some thing 161',
    description: 'Description for Todo list item number 161',
    color: 'DARKER_GREEN',
  },
  {
    id: '162',
    name: 'Do some thing 162',
    description: 'Description for Todo list item number 162',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '163',
    name: 'Do some thing 163',
    description: 'Description for Todo list item number 163',
    color: 'DARKER_GREEN',
  },
  {
    id: '164',
    name: 'Do some thing 164',
    description: 'Description for Todo list item number 164',
    color: 'DARKEST_GREEN',
  },
  {
    id: '165',
    name: 'Do some thing 165',
    description: 'Description for Todo list item number 165',
    color: 'GREEN',
  },
  {
    id: '166',
    name: 'Do some thing 166',
    description: 'Description for Todo list item number 166',
    color: 'DARKER_GREEN',
  },
  {
    id: '167',
    name: 'Do some thing 167',
    description: 'Description for Todo list item number 167',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '168',
    name: 'Do some thing 168',
    description: 'Description for Todo list item number 168',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '169',
    name: 'Do some thing 169',
    description: 'Description for Todo list item number 169',
    color: 'DARKEST_GREEN',
  },
  {
    id: '170',
    name: 'Do some thing 170',
    description: 'Description for Todo list item number 170',
    color: 'GREEN',
  },
  {
    id: '171',
    name: 'Do some thing 171',
    description: 'Description for Todo list item number 171',
    color: 'DARKER_GREEN',
  },
  {
    id: '172',
    name: 'Do some thing 172',
    description: 'Description for Todo list item number 172',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '173',
    name: 'Do some thing 173',
    description: 'Description for Todo list item number 173',
    color: 'DARKEST_GREEN',
  },
  {
    id: '174',
    name: 'Do some thing 174',
    description: 'Description for Todo list item number 174',
    color: 'DARKER_GREEN',
  },
  {
    id: '175',
    name: 'Do some thing 175',
    description: 'Description for Todo list item number 175',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '176',
    name: 'Do some thing 176',
    description: 'Description for Todo list item number 176',
    color: 'DARKEST_GREEN',
  },
  {
    id: '177',
    name: 'Do some thing 177',
    description: 'Description for Todo list item number 177',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '178',
    name: 'Do some thing 178',
    description: 'Description for Todo list item number 178',
    color: 'GREEN',
  },
  {
    id: '179',
    name: 'Do some thing 179',
    description: 'Description for Todo list item number 179',
    color: 'DARKER_GREEN',
  },
  {
    id: '180',
    name: 'Do some thing 180',
    description: 'Description for Todo list item number 180',
    color: 'DARKER_GREEN',
  },
  {
    id: '181',
    name: 'Do some thing 181',
    description: 'Description for Todo list item number 181',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '182',
    name: 'Do some thing 182',
    description: 'Description for Todo list item number 182',
    color: 'DARKEST_GREEN',
  },
  {
    id: '183',
    name: 'Do some thing 183',
    description: 'Description for Todo list item number 183',
    color: 'DARKER_GREEN',
  },
  {
    id: '184',
    name: 'Do some thing 184',
    description: 'Description for Todo list item number 184',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '185',
    name: 'Do some thing 185',
    description: 'Description for Todo list item number 185',
    color: 'GREEN',
  },
  {
    id: '186',
    name: 'Do some thing 186',
    description: 'Description for Todo list item number 186',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '187',
    name: 'Do some thing 187',
    description: 'Description for Todo list item number 187',
    color: 'DARKER_GREEN',
  },
  {
    id: '188',
    name: 'Do some thing 188',
    description: 'Description for Todo list item number 188',
    color: 'DARKEST_GREEN',
  },
  {
    id: '189',
    name: 'Do some thing 189',
    description: 'Description for Todo list item number 189',
    color: 'DARKER_GREEN',
  },
  {
    id: '190',
    name: 'Do some thing 190',
    description: 'Description for Todo list item number 190',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '191',
    name: 'Do some thing 191',
    description: 'Description for Todo list item number 191',
    color: 'GREEN',
  },
  {
    id: '192',
    name: 'Do some thing 192',
    description: 'Description for Todo list item number 192',
    color: 'LIGHTEST_GREEN',
  },
  {
    id: '193',
    name: 'Do some thing 193',
    description: 'Description for Todo list item number 193',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '194',
    name: 'Do some thing 194',
    description: 'Description for Todo list item number 194',
    color: 'DARKEST_GREEN',
  },
  {
    id: '195',
    name: 'Do some thing 195',
    description: 'Description for Todo list item number 195',
    color: 'DARKER_GREEN',
  },
  {
    id: '196',
    name: 'Do some thing 196',
    description: 'Description for Todo list item number 196',
    color: 'LIGHTER_GREEN',
  },
  {
    id: '197',
    name: 'Do some thing 197',
    description: 'Description for Todo list item number 197',
    color: 'GREEN',
  },
  {
    id: '198',
    name: 'Do some thing 198',
    description: 'Description for Todo list item number 198',
    color: 'DARKER_GREEN',
  },
  {
    id: '199',
    name: 'Do some thing 199',
    description: 'Description for Todo list item number 199',
    color: 'DARKEST_GREEN',
  },
  {
    id: '200',
    name: 'Do some thing 200',
    description: 'Description for Todo list item number 200',
    color: 'DARKER_GREEN',
  },
];
